# Generated by Django 6.0.2 on 2026-02-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ma_page_web', '0002_article_resume_alter_article_id_alter_article_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('ORDINATEUR', 'Ordinateur'), ('TELEPHONE', 'Téléphone')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
